#!/usr/bin/with-contenv sh

[ -e /homebridge/logs ] || mkdir -p /homebridge/logs
[ -e /homebridge/logs/homebridge.log ] || touch /homebridge/logs/homebridge.log

chown -R abc:abc /homebridge/logs/homebridge.log

exec s6-setuidgid abc tail -f --follow=name /homebridge/logs/homebridge.log
