name: Support Request
description: Need help?
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please read the following before you start filling out this form:
        
        * If your issue is specific to a certain plugin, create the issue on that plugin's GitHub project page instead.
        * Support via GitHub issues is limited. You may find it more benefitial ask questions on the [Homebridge Discord](https://discord.gg/kqNCe2D) or [Reddit](https://www.reddit.com/r/homebridge/) communities instead.
        * Search through existing issues (resolved or open) which might provide a solution to your problem already.
        * Aim to find a descriptive and precise title for your support request.
  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: |
        Please provide an overview of the current situation and illustrate potential problems or shortcomings.
        
        * What is happening?
        * What you expect to happen?
        * Clear steps explaining how to reproduce the problem.
      placeholder: |
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: text
      description: |
        Please provide the relevant logs showing the error that occurred.

        * Keep this short. Do not paste in hundereds of lines repeating the same error.
        * Show the logs from the service being restarted until the error is occurs.
    validations:
      required: false
  - type: textarea
    id: docker-config
    attributes:
      label: Docker Config
      render: yml
      description: |
        Please include your `docker run ...` command or `docker-compose.yml` file.
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: Host Operating System
      options:
        - Raspberry Pi OS / Raspbian
        - Ubuntu / Debian (or a variant)
        - Fedora / CentOS / RedHat (or a variant)
        - Synology DSM
        - QNAP
        - Unraid
        - Other (specify in description)
      description: |
        If your operating system is not listed, please provide it in the bug description.

        **Please note that macOS and Windows are not supported as host operating systems. [See this for more info](https://github.com/oznu/docker-homebridge#compatibility).**
    validations:
      required: true