#!/usr/bin/with-localenv sh

# ensure log file exists
touch /homebridge/homebridge.log

# fix permissions
chown -R abc:abc /homebridge

# wait for services to come up
sleep 2

# ensure the ui knows it's running in docker
export HOMEBRIDGE_CONFIG_UI=1
export HOMEBRIDGE_INSECURE=1

s6-setuidgid root hb-service run \
  --allow-root \
  --docker \
  --uid=$(id abc -u) \
  --gid=$(id abc -g) \
  -I \
  -U /homebridge \
  -P /homebridge/node_modules
