language: bash

services:
  - docker

env:
  - S6_ARCH=amd64 DOCKERFILE="Dockerfile" AVAHI=1 TAG_SUFFIX=""
  - S6_ARCH=amd64 DOCKERFILE="Dockerfile" AVAHI=0 TAG_SUFFIX="no-avahi"
  - S6_ARCH=amd64 DOCKERFILE="Dockerfile.debian" AVAHI=1 TAG_SUFFIX="debian"
  - S6_ARCH=amd64 DOCKERFILE="Dockerfile.debian" AVAHI=0 TAG_SUFFIX="debian-no-avahi"

  - S6_ARCH=armhf DOCKERFILE="Dockerfile" AVAHI=1 TAG_SUFFIX="raspberry-pi"
  - S6_ARCH=armhf DOCKERFILE="Dockerfile" AVAHI=0 TAG_SUFFIX="no-avahi-raspberry-pi"
  - S6_ARCH=armhf DOCKERFILE="Dockerfile.debian" AVAHI=1 TAG_SUFFIX="debian-raspberry-pi"
  - S6_ARCH=armhf DOCKERFILE="Dockerfile.debian" AVAHI=0 TAG_SUFFIX="debian-no-avahi-raspberry-pi"

  - S6_ARCH=aarch64 DOCKERFILE="Dockerfile" AVAHI=1 TAG_SUFFIX="aarch64"
  - S6_ARCH=aarch64 DOCKERFILE="Dockerfile" AVAHI=0 TAG_SUFFIX="no-avahi-aarch64"

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - export TARGET_IMAGE_TAG=$(if [ "$TRAVIS_BRANCH" = "master" ]; then if [ "$TAG_SUFFIX" = "" ]; then echo "latest"; else echo "$TAG_SUFFIX"; fi; else if [ "$TAG_SUFFIX" = "" ]; then echo "$TRAVIS_BRANCH"; else echo "$TRAVIS_BRANCH-$TAG_SUFFIX"; fi; fi)
  - docker pull $TARGET_IMAGE:$TARGET_IMAGE_TAG && export IMAGE_CACHE="--cache-from $TARGET_IMAGE:$TARGET_IMAGE_TAG" || export IMAGE_CACHE=""

script:
  - docker build -f $DOCKERFILE $IMAGE_CACHE --build-arg S6_ARCH=$S6_ARCH --build-arg AVAHI=$AVAHI -t $TARGET_IMAGE:$TARGET_IMAGE_TAG .
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker push $TARGET_IMAGE:$TARGET_IMAGE_TAG