#!/command/with-contenv sh

[ -e /homebridge/homebridge.log ] || touch /homebridge/homebridge.log

chown $PUID:$PGID /homebridge/homebridge.log

exec s6-setuidgid $PUID:$PGID tail -f --follow=name /homebridge/homebridge.log
