#!/command/with-contenv sh

[ -e /homebridge/homebridge.log ] || touch /homebridge/homebridge.log

chown homebridge: /homebridge/homebridge.log

exec s6-setuidgid homebridge tail -f --follow=name /homebridge/homebridge.log
