#!/command/with-contenv sh

if [ "$ENABLE_AVAHI" = "1" ]; then
  echo "Starting dbus-daemon"
  exec dbus-daemon --system --nofork
else
  echo "Avahi disabled, not starting dbus-daemon"
  exec sleep infinity
fi

