name: Beta Stage 2 - Trigger Beta Release

# this is just a stub to allow reuse of Beta Stage 1 from homebridge-apt-pkg

on:
  workflow_dispatch:
jobs:
  trigger-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build and Push Docker Images
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build_and_push.yml', // Replace with the actual filename of the target workflow
              ref: 'latest',
              inputs: {
                release_type: 'beta'
              }
            });