#!/usr/bin/with-contenv sh

. /etc/os-release

# fix /etc/sudo.conf permissions
chmod 440 /etc/sudo.conf

# parse extra packages list
if [ ! -z "$PACKAGES" ]; then

  for job in $(echo "$PACKAGES" | tr "," " "); do
    export EXTRA_PACKAGES="$EXTRA_PACKAGES ${job}"
  done

  echo "Installing extra packages for $ID linux: $EXTRA_PACKAGES"

  if [ "$ID" = "alpine" ]; then
    apk add $EXTRA_PACKAGES
  elif [ "$ID" = "ubuntu" ]; then
    apt-get update && apt-get install -y $EXTRA_PACKAGES
  fi

  if [ $? -ne 0 ]; then
    echo
    echo "--------------------------------------------------------------"
    echo "ERROR INSTALLING CUSTOM PACKAGES"
    echo "--------------------------------------------------------------"
    echo "Failed to install custom packages. See log above for details."
    echo "Please ensure all packages requested are named correctly."
    [ "$ID" = "alpine" ] && echo
    [ "$ID" = "alpine" ] && echo "A full list of available packages can be found here:"
    [ "$ID" = "alpine" ] && echo "https://pkgs.alpinelinux.org/packages"
    echo "--------------------------------------------------------------"
    echo
  fi

fi
