#!/usr/bin/with-contenv sh

if [ "$HOMEBRIDGE_CONFIG_UI" = "1" ]; then
  echo "Enabling homebridge-config-ui-x..."

  # install homebridge-config-ui-x on first run
  [[ -f /usr/local/lib/node_modules/homebridge-config-ui-x/package.json ]] || npm install -g --unsafe-perm homebridge-config-ui-x

  # enable homebridge-config-ui-x service
  [[ -e /etc/services.d/homebridge-config-ui-x ]] || mv /etc/services.d/.homebridge-config-ui-x /etc/services.d/homebridge-config-ui-x
else
  # disable homebridge-config-ui-x service
  [[ -e /etc/services.d/homebridge-config-ui-x ]] && mv /etc/services.d/homebridge-config-ui-x /etc/services.d/.homebridge-config-ui-x
fi
