#!/usr/bin/with-contenv sh

# make folders
mkdir -p /var/run/dbus
mkdir -p /var/run/avahi-daemon

# delete existing pid if found
[[ -e /var/run/dbus.pid ]] && rm -f /var/run/dbus.pid
[[ -e /var/run/avahi-daemon/pid ]] && rm -f /var/run/avahi-daemon/pid

# permissions
chown messagebus:messagebus /var/run/dbus
chown avahi:avahi /var/run/avahi-daemon
dbus-uuidgen --ensure
sleep 1
