#!/usr/bin/with-contenv sh

if [ "$ENABLE_AVAHI" = "1" ]; then
  echo "Enabling Avahi..."
  # enable avahi
  [ -e /etc/services.d/.dbus ] && mv /etc/services.d/.dbus /etc/services.d/dbus
  [ -e /etc/services.d/.avahi ] && mv /etc/services.d/.avahi /etc/services.d/avahi

  # make folders
  mkdir -p /var/run/dbus
  mkdir -p /var/run/avahi-daemon

  # delete existing pid if found
  [ -e /var/run/dbus.pid ] && rm -f /var/run/dbus.pid
  [ -e /var/run/dbus/pid ] && rm -f /var/run/dbus/pid
  [ -e /var/run/avahi-daemon/pid ] && rm -f /var/run/avahi-daemon/pid

  # permissions
  chown messagebus:messagebus /var/run/dbus
  chown avahi:avahi /var/run/avahi-daemon
  dbus-uuidgen --ensure
  sleep 1

  # avahi config
  cp /defaults/avahi-daemon.conf /etc/avahi/avahi-daemon.conf

  # fix for synology dsm - see #35
  if [ ! -z "$DSM_HOSTNAME" ]; then
    sed -i "s/.*host-name.*/host-name=${DSM_HOSTNAME}/" /etc/avahi/avahi-daemon.conf
  else
    sed -i "s/.*host-name.*/#host-name=/" /etc/avahi/avahi-daemon.conf
  fi
else
  # disable avahi
  [ -e /etc/services.d/dbus ] && mv /etc/services.d/dbus /etc/services.d/.dbus
  [ -e /etc/services.d/avahi ] && mv /etc/services.d/avahi /etc/services.d/.avahi
fi

