#!/usr/bin/with-contenv sh

# create default files
[[ -e /homebridge/package.json ]] || cp /defaults/package.json /homebridge/package.json
[[ -e /homebridge/config.json ]] || cp /defaults/config.json /homebridge/config.json
[[ -e /homebridge/startup.sh ]] || cp /defaults/startup.sh /homebridge/startup.sh

# run user defined custom startup script
chmod +x /homebridge/startup.sh
exec /homebridge/startup.sh
