#!/usr/bin/with-contenv sh

# create default files
[ -e /homebridge/config.json ] || /usr/bin/homebridge-generate-config
[ -e /homebridge/package.json ] || cp /defaults/package.json /homebridge/package.json
[ -e /homebridge/startup.sh ] || cp /defaults/startup.sh /homebridge/startup.sh
[ -e /homebridge/.docker.env ] || cp /defaults/.docker.env /homebridge/.docker.env
[ -e /homebridge/logs ] || mkdir -p /homebridge/logs

# run user defined custom startup script
chmod +x /homebridge/startup.sh
exec /homebridge/startup.sh
