#!/usr/bin/with-contenv sh

[ -f /homebridge/package.json ] || cp /defaults/package.json /homebridge/package.json
[ -f /homebridge/config.json ] || cp /defaults/config.json /homebridge/config.json

echo "Homebridge: Removing old plugins..."
npm prune
echo "Homebridge: Installing plugins..."
yarn install

chown -R abc:abc /homebridge
