#!/usr/bin/with-contenv sh

/usr/bin/container-credits-banner

# remove synology @eaDir from node_modules
[ -e /homebridge/node_modules/@eaDir ] && rm -rf /homebridge/node_modules/@eaDir

# install plugins defined in the package.json file, prune others.
echo "Homebridge: Installing plugins..."
npm prune
npm install --unsafe-perm --production

# fix permissions
chown -R abc:abc /homebridge

# change owner of root home dir
chown abc:abc /root