#!/usr/bin/with-contenv sh

if [ "$HOMEBRIDGE_CONFIG_UI" = "1" ] || homebridge-ui-configured; then
  echo "Enabling homebridge-config-ui-x..."
  # enable homebridge-config-ui-x service
  [ -e /etc/services.d/.homebridge-config-ui-x ] && mv /etc/services.d/.homebridge-config-ui-x /etc/services.d/homebridge-config-ui-x
  [ -e /etc/services.d/.hb-service-logs ] && mv /etc/services.d/.hb-service-logs /etc/services.d/hb-service-logs

  # disable homebridge
  [ -e /etc/services.d/homebridge ] && mv /etc/services.d/homebridge /etc/services.d/.homebridge

  # check homebridge-config-ui-x is not installed in /homebridge/node_modules
  [ -e /homebridge/node_modules/homebridge-config-ui-x ] && npm uninstall --save homebridge-config-ui-x

  # check to see if an offline update to the @latest was requested
  if [ -e /homebridge/.uix-upgrade-on-restart ]; then
    echo "Updating Homebridge Config UI X to latest version; this might take a few minutes..."
    npm install -g --unsafe-perm homebridge-config-ui-x@latest && rm -rf /homebridge/.uix-upgrade-on-restart
  fi
else
  # disable homebridge-config-ui-x service
  [ -e /etc/services.d/homebridge-config-ui-x ] && mv /etc/services.d/homebridge-config-ui-x /etc/services.d/.homebridge-config-ui-x
  [ -e /etc/services.d/hb-service-logs ] && mv /etc/services.d/hb-service-logs /etc/services.d/.hb-service-logs

  # enable homebridge service
  [ -e /etc/services.d/.homebridge ] && mv /etc/services.d/.homebridge /etc/services.d/homebridge
fi